# Generated by Django 2.2.4 on 2019-11-11 18:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolistapp', '0004_todo_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='like',
        ),
        migrations.AddField(
            model_name='todo',
            name='like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
